name = "apea-aiken-batch-1/crowdfunding_b"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'apea-aiken-batch-1/crowdfunding_b'"

[repository]
user = "apea-aiken-batch-1"
project = "crowdfunding_b"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.220.202412"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "2.220.202412"
source = "github"

[config.default]
state_token = "STATE_TOKEN"
